# version: '3.8'
services:
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: valkey_db
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
  
  quadrant:
    image: qdrant/qdrant:latest
    container_name: quadrant_db
    ports:
      - "6333:6333" # API port
      - "6334:6334" # gRPC port
    volumes:
      - quadrant_data:/qdrant/storage

volumes:
  valkey_data:
  quadrant_data: